"""Type stubs for ComfyUI folder_paths module."""

from typing import List, Optional, Dict, Tuple, Set

base_path: str
models_dir: str
folder_names_and_paths: Dict[str, Tuple[List[str], Set[str]]]
supported_pt_extensions: Set[str]

def get_filename_list(folder_name: str) -> List[str]: ...
def get_full_path(folder_name: str, filename: str) -> Optional[str]: ...
def get_folder_paths(folder_name: str) -> List[str]: ...
def get_input_directory() -> str: ...
def get_output_directory() -> str: ...
def get_annotated_filepath(filename: str) -> str: ...
