"""Type stubs for ComfyUI comfy.model_management module."""

from typing import Any, Callable, Optional

def get_torch_device() -> Any: ...
def text_encoder_device() -> Any: ...
def xformers_enabled() -> bool: ...

