"""Type stubs for ComfyUI comfy.model_management module."""

from typing import Any, Callable, Optional, List

def get_torch_device() -> Any: ...
def text_encoder_device() -> Any: ...
def xformers_enabled() -> bool: ...
def get_total_memory(device: Any = None) -> int: ...
def get_free_memory(device: Any = None) -> int: ...

# Current loaded models list
current_loaded_models: List[Any]

