"""Type stubs for ComfyUI comfy.utils module."""

from typing import Any, Callable

class ProgressBar:
    def __init__(self, total: int) -> None: ...
    def update(self, value: int) -> None: ...
    def update_absolute(self, value: int, total: int = ..., preview: Any = ...) -> None: ...
